
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynkkdrfgzrurlhoalblz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlua2tkcmZnenJ1cmxob2FsYmx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMjQyMDQsImV4cCI6MjA1ODYwMDIwNH0.UWuWONJhoTFuutaBXmzHay382Kwb0zAnZBrXsBpb8Gw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: fetch,
  },
  db: {
    schema: 'public',
  },
  storage: {
    retryIntervals: 500,
    maxRetryCount: 2,
  },
});
